title Installing...
pip install pystyle
pip install shutil
pip install marshal
pip install zlib
pip install threading
pip install requests
pip install random
pip install discord
pip install roblox-mod
pip install discord.py
pip install colorama
pip install time
pip install webbrowser
pip install subprocess
pip install base64
pip install re
pip install b64encode
pip install shutil
pip install itertools
pip install randint
pip install httpx
title PRIME TOOLS
